# Generated by Django 2.2.6 on 2019-11-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('id_num', models.PositiveIntegerField()),
                ('organiser', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('event_about', models.TextField()),
                ('event_image', models.FileField(upload_to='')),
            ],
        ),
    ]
